from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum


class CrawlStatus(str, Enum):
    """Lifecycle status for crawl targets."""

    NEEDS_RENDER = "needs_render"
    FAILED = "failed"
    CRAWLED = "crawled"


@dataclass(slots=True)
class UrlRecord:
    """Track status and crawl metadata for a URL."""

    url: str
    status: CrawlStatus
    attempts: int = 0
    last_error: str | None = None
    fetched_at: datetime | None = None


@dataclass(slots=True)
class ExtractedContent:
    """Normalized extracted content from source documents."""

    title: str
    headings: list[str] = field(default_factory=list)
    body: str = ""
    code_blocks: list[str] = field(default_factory=list)
    tables: list[str] = field(default_factory=list)
    admonitions: list[str] = field(default_factory=list)


@dataclass(slots=True)
class CrawlDocument:
    """Persistable document generated by the crawler."""

    doc_id: str
    url: str
    canonical_url: str
    source_type: str
    extracted: ExtractedContent
    status: CrawlStatus = CrawlStatus.CRAWLED
    etag: str | None = None
    last_modified: str | None = None
    crawled_at: datetime = field(default_factory=datetime.utcnow)


@dataclass(slots=True)
class CrawlResult:
    """End-to-end crawl output for indexing pipeline."""

    document: CrawlDocument
    chunks: list[dict[str, str]]
    embedding_enqueued: bool = False
